import system.file;
import system.io;
import system.memory;
import system.path;
import system.process;
import system.text;

unsafe IrContext backend_base_context(
    text project_source,
    text project_root,
    ptr byte module_data,
    PackedBuffer modules,
    ptr byte source_data,
    ptr byte type_data,
    PackedBuffer types,
    ptr byte symbol_data,
    ptr byte detail_data,
    PackedBuffer symbols,
    usize next_value
) {
    return IrContext{
        project_source = project_source,
        project_root = project_root,
        source = "",
        module_data = ir_pointer_alias(module_data),
        modules = modules,
        source_data = ir_pointer_alias(source_data),
        type_data = ir_pointer_alias(type_data),
        types = types,
        symbol_data = ir_pointer_alias(symbol_data),
        detail_data = ir_pointer_alias(detail_data),
        symbols = symbols,
        token_data = null,
        tokens = PackedBuffer{ length = 0, capacity = 0 },
        syntax_data = null,
        syntax = PackedBuffer{ length = 0, capacity = 0 },
        module_index = 0,
        source_record = 0,
        function_node = 0,
        function_symbol = 0,
        function_result = 0,
        function_local_first = 0,
        function_local_end = 0,
        name_cache = null,
        spelling_cache = null,
        spelling_cache_capacity = 0,
        call_cache = null,
        call_argument_first = null,
        call_argument_last = null,
        argument_next = null,
        type_cache = null,
        resolved_type_ref_cache = null,
        left_expression_cache = null,
        right_expression_cache = null,
        block_parent_cache = null,
        control_parent_cache = null,
        statement_nodes = null,
        statement_count = 0,
        block_statement_first = null,
        statement_next = null,
        control_block_first = null,
        block_next = null,
        control_child_first = null,
        control_child_next = null,
        initializer_field_first = null,
        initializer_field_next = null,
        initializer_field_owner = null,
        array_element_first = null,
        array_element_next = null,
        block_nodes = null,
        block_count = 0,
        control_nodes = null,
        control_count = 0,
        expression_nodes = null,
        expression_count = 0,
        call_nodes = null,
        call_count = 0,
        expression_start_heads = null,
        expression_start_capacity = 0,
        expression_start_next = null,
        expression_next_start = null,
        function_at_position = null,
        name_nodes = null,
        name_count = 0,
        type_ref_nodes = null,
        type_ref_count = 0,
        declaration_symbol_cache = null,
        top_symbols = null,
        top_symbol_count = 0,
        function_bucket_heads = null,
        function_bucket_capacity = 0,
        function_bucket_next = null,
        function_parameter_first = null,
        function_parameter_count = null,
        parameter_next = null,
        function_local_range_first = null,
        function_local_range_end = null,
        type_aggregate_symbols = null,
        aggregate_field_first = null,
        field_next = null,
        enum_item_value = null,
        symbol_export_cache = null,
        native_layout_size_cache = null,
        native_layout_alignment_cache = null,
        native_layout_state_cache = null,
        local_values = null,
        block_data = null,
        blocks = PackedBuffer{ length = 0, capacity = 0 },
        instruction_data = null,
        instruction_detail = null,
        instructions = PackedBuffer{ length = 0, capacity = 0 },
        operand_data = null,
        operands = PackedBuffer{ length = 0, capacity = 0 },
        break_data = null,
        break_depth = 0,
        continue_data = null,
        continue_depth = 0,
        current_block = 0,
        next_value = next_value,
        profile_statement_candidates = 0,
        profile_parent_candidates = 0,
        profile_expression_positions = 0,
        profile_syntax_candidates = 0,
        profile_symbol_candidates = 0
    };
}
