import system.file;
import system.io;
import system.memory;
import system.path;

unsafe bool winmd_emit_module(
    ref WinmdReader reader,
    usize module,
    text output_directory,
    ref DBuffer hashes,
    ptr byte stats_data
) {
    DBuffer output = d_buffer_create(67108864);
    d_put(output, "// Generated by openc-winmd-projector-sh17.1; DO NOT EDIT.\n");
    d_put(output, "// schema=openc.windows_raw_projection.v1\n");
    d_put(output, "// metadata-version="); d_put(output, winmd_pinned_package_version());
    d_put(output, "\n// metadata-sha256="); d_put(output, winmd_pinned_sha256());
    d_put(output, "\n// architecture=x86_64\n");
    d_put(output, "// strings and blobs are exact lowercase hexadecimal UTF-8/bytes.\n");
    d_put(output, "// records: R=typeref D=dll T=type F=field M=method P=param X=interface I=import C=constant L=class-layout O=field-offset A=attribute\n\n");
    WinmdProjectionStats stats = winmd_projection_stats();
    if module == winmd_module_foundation() {
        winmd_emit_type_refs(reader, output, stats);
    }
    winmd_emit_types_and_members(reader, module, output, stats);
    winmd_emit_interfaces(reader, module, output, stats);
    winmd_emit_imports(reader, module, output, stats);
    winmd_emit_constants(reader, module, output, stats);
    winmd_emit_layouts(reader, module, output, stats);
    winmd_emit_custom_attributes(reader, module, output, stats);
    winmd_emit_module_footer(module, output, stats);
    if !reader.ok || !output.ok {
        d_buffer_destroy(output); return false;
    }
    text destination = path.join(
        output_directory, winmd_module_file_name(module)
    );
    status written = file.write_text(destination, d_buffer_text(output));
    if !written.ok { d_buffer_destroy(output); return false; }
    winmd_sha256_hex(output.data, output.length, hashes);
    d_put(hashes, "\n");
    usize base = module * 10 * size_of(usize);
    memory.store_usize(stats_data + base + 0 * size_of(usize), stats.records);
    memory.store_usize(stats_data + base + 1 * size_of(usize), stats.types);
    memory.store_usize(stats_data + base + 2 * size_of(usize), stats.fields);
    memory.store_usize(stats_data + base + 3 * size_of(usize), stats.methods);
    memory.store_usize(stats_data + base + 4 * size_of(usize), stats.parameters);
    memory.store_usize(stats_data + base + 5 * size_of(usize), stats.imports);
    memory.store_usize(stats_data + base + 6 * size_of(usize), stats.constants);
    memory.store_usize(stats_data + base + 7 * size_of(usize), stats.custom_attributes);
    memory.store_usize(stats_data + base + 8 * size_of(usize), stats.class_layouts);
    memory.store_usize(stats_data + base + 9 * size_of(usize), stats.field_layouts);
    d_buffer_destroy(output);
    return true;
}

unsafe usize winmd_saved_stat(
    ptr byte stats_data,
    usize module,
    usize field
) {
    return memory.load_usize(
        stats_data + (module * 10 + field) * size_of(usize)
    );
}

unsafe void winmd_put_json_stat(
    ref DBuffer manifest,
    text name,
    usize value,
    bool comma
) {
    d_put(manifest, "      \""); d_put(manifest, name); d_put(manifest, "\": ");
    d_put_usize(manifest, value);
    if comma { d_put(manifest, ","); }
    d_put(manifest, "\n");
}
